{% set name = "schwimmbad" %}
{% set version = "0.3.2" %}
{% set sha256 = "d453b735fcd0d4a5c5a6e18af2f72f678358f7614db3b78b6cd38d6b07debc9f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm
    - six
  run:
    - python
    - setuptools
    - six
    - mpi4py  # [not win]

test:
  imports:
    - schwimmbad

about:
  home: http://github.com/adrn/schwimmbad
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A common interface for parallel processing pools

  description: |
    schwimmbad enables easy switching between serial execution, multiprocessing,
    and MPI by providing a common interface.
  doc_url: https://github.com/adrn/schwimmbad
  dev_url: https://github.com/adrn/schwimmbad

extra:
  recipe-maintainers:
    - guillochon
    - pkgw
    - adrn
