{% set name = "schwimmbad" %}
{% set version = "0.4.0" %}
{% set sha256 = "8063c8c6cb7ad262b19f50b1b8badd6967be88f5d6bb52b5d417cc4d214e30ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - dill
    - hatchling
    - hatch-vcs
    - multiprocess
    - pip
    - python
  run:
    - dill
    - multiprocess
    - python
    - mpi4py  # [not win]

test:
  imports:
    - schwimmbad

about:
  home: http://github.com/adrn/schwimmbad
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A common interface for parallel processing pools

  description: |
    schwimmbad enables easy switching between serial execution, multiprocessing,
    and MPI by providing a common interface.
  doc_url: https://github.com/adrn/schwimmbad
  dev_url: https://github.com/adrn/schwimmbad

extra:
  recipe-maintainers:
    - guillochon
    - pkgw
    - adrn
