{% set name = "schwimmbad" %}
{% set version = "0.3.0" %}
{% set sha256 = "a4ba583cf71003f51ea1a9017d5a7d6a25d359a6adc25d4affa14d1abfec75a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - six
  run:
    - python
    - six
    - mpi4py

test:
  imports:
    - schwimmbad

about:
  home: http://github.com/adrn/schwimmbad
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A common interface for parallel processing pools'

  description: |
    schwimmbad enables easy switching between serial execution, multiprocessing,
    and MPI by providing a common interface.
  doc_url: https://github.com/adrn/schwimmbad
  dev_url: https://github.com/adrn/schwimmbad

extra:
  recipe-maintainers:
    - guillochon
    - pkgw
    - adrn
