travis:
  secure:
    BINSTAR_TOKEN: RKK4LGAhoyA4FmfnQ2fCbwx6Vvmr99HfpxGJAlPlJdhyJ05tBpLu2nAZsgch5wXyIR2p6U2ghKyFwYVWhxWD17AMrkbowwS5KO8lTLqJWDDXL973GGIbmVEMc61qpPpyfIzMebTmMm6e2KqBxTfcjd7OzSZo9LEHKgwpflVFcj06SnbqEzPIJKazh7enAh1q5XfH0gdNHHLQ89cyecXqWGjA78kE5cclLxi000aoyBzZQzUHNmzPa1TuksapxDNDftUmXA9W3FG0EMa00webxj9mFKYF4ZkXiCRhMKcSdxFuYY3GY0UAK3JLC6i45OoNkn6IDyWwV+e8onkydProj5ziILFByB7lfo5cKPB5+EnE4406jv3vCZhzSUYbEiVwmKyr2Byy1n1J3Do+DVOoIQDPEsCVIaPfEt5CZduTe4MqOjUSp2iFJTSlc12NzyCuxinNrX8LbDNTL8t0thfzNyny0I8SebJDv/z9e59HirJShKdNkPwghT8CcVavsmuvuEPDPPpxs7CZeffuXYp3ZMsk7h9eaPgG2lwzH59haz4vFPBwZlG3GwJD3BCs1GWkB1BxiDk9A/WewN3AXVaeV1gW+NYIY+OFDnZmiBtQJCOTUX5Zl72QtlvIIWT45YlKkDGx1jT0XizuBk/M3gLBS0Dw7ZFHwclHzxjoUuciBVA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
