appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GHByPEddpXjm7cVJHotzV5v6PbhVDrmxULn1/x+PBJjpLkOqoNlFkdryHeLH9GC6lpkzhSOap+Dfr9Brsl9N9Ox61i/ceMnOJ7TgqfoDuY8NwdunbJqCK6AGEydsWTsb40x8VNjfihGv6gKgaNr9Nhn3IhAnkyrwcnOPj7qlbR+fHbU/M6Quey0Q5CA/8YcnpQQ6filzRSIUsUEW9Eb8i7ybBxvNbZSZfdp/ky3/MLUJBL9+Z0C/pupMq9F0rWnKwlpOTpeP9K4P/k0aoKwJVfOOAxNfWeGzwKNz5+IwMXeVm3TufAtRoteGUStL79ADq1YqH/nBidORCGlI3JfV+/uTkEbGPlYy1zVoc50aYjaZqIFaic7xhpIJLOh2bU+Mkgcsz8qxGqbM0envlNWx5roijiRVeV2IkLbDfQCHyUWhHaPFfUqqBqZxBup8q5/d4wEAIu99SmF3tRg2KoGqt30aq+UrddC+rHIM45H3NC+VZXmmCZRfycdOu6TlVc0gh23/wKCbFu45BK1T7RDzAuCjztnIF+rwqyqLZwFs+Pw+iU43XFHzPAvrEPQGRIk6R4u1cY2S1NUvGpqeCIceu+HeRLIJNLU7hE+YN81GbV0JrqZVJHfHvSP7CR1u5womLgvtP/SnyU5VtO7Ft2P7T+Im3c8vVF31XmNzCodYsdQ=}
provider:
  win: azure
